### ISSUE TITLE
Action.ts CreateCommand updates previous selected callers, variables and feedbacks before command is sent

### ISSUE THREAD

**Issue by digitaldrummerj** [bitfocus/companion-module-zoom-osc-iso#116]
Looking at the action.ts CreateCommand function, it is saving the selected callers to the previous selected callers, updating the variables and updating the feedback but an OSC command has not been sent yet.  It feels like the update to the callers, variables and feedbacks should only happen after the command has been sent which I believe is already being done as part of the OSC processData function as it gets an OSC message sent after the commands.  

So the question is should the module be updating the previous selected callers, variables, and feedback at all in the create command function?

**Comment by JeffreyDavidsz** [comment]
This was done because of the clear selection, that was happening after each command. Later we have chosen to keep selection and let users clear selection. So for that reason it's indeed double now. The other thing is to make sure that any local changes are directly reflected instead of waiting for the OSC to arrive. But agree this is not the right place anymore to do so. Should only be a function to create the propper command.
