### ISSUE TITLE
Crashes on V3

### ISSUE THREAD

**Issue by DanielWilliamsMSC** [bitfocus/companion-module-zoom-osc-iso#122]
Experiencing random crashes on Companion3 RC1 and BETA 

````
TypeError: Cannot read properties of undefined (reading 'users')
    at t.OSC.processData (C:\Program Files\Companion\resources\bundled-modules\zoom-osc-iso\main.js:2:316311)
    at r.UDPPort.<anonymous> (C:\Program Files\Companion\resources\bundled-modules\zoom-osc-iso\main.js:2:310995)
    at r.UDPPort.emit (node:events:513:28)
    at r.UDPPort.emit (node:domain:489:12)
    at n.firePacketEvents (C:\Program Files\Companion\resources\bundled-modules\zoom-osc-iso\main.js:2:626771)
    at t.decodeOSC (C:\Program Files\Companion\resources\bundled-modules\zoom-osc-iso\main.js:2:627686)
    at r.UDPPort.emit (node:events:513:28)
    at r.UDPPort.emit (node:domain:489:12)
    at Socket.<anonymous> (C:\Program Files\Companion\resources\bundled-modules\zoom-osc-iso\main.js:2:642736)
    at Socket.emit (node:events:513:28)

```

**Comment by DanielWilliamsMSC** [comment]
Seems to be random.

Thus particular one was joining a meeting. But I'm also seeing it when selecting members and trying to admit.

Get Outlook for Android<https://aka.ms/AAb9ysg>

Daniel WilliamsNetwork Security and Systems Specialist
MailPO Box 18, Ballan, Vic 3342
Ballan15 Stead St, Ballan
Bacchus Marsh215 Main St, Bacchus Marsh
Darley182 Halletts Way, Darley
Phone(03) 5366 7100
Email
***@***.***
Websitemoorabool.vic.gov.au
ABN293 5275 4296
________________________________

**Comment by digitaldrummerj** [comment]
@DanielWilliamsMSC  I have not been able to replicate this in the 2 events I have run over the past week.  Can you provide a little bit more information for me:

* Which operating system (Mac or Windows)?
* Are you using ZoomOSC or ZoomISO?
* Which version of ZoomOSC or ZoomISO are you using?
* Are you using the Pro or Lite version for ZoomOSC/ZoomISO?

**Comment by DanielWilliamsMSC** [comment]
Which operating system (Mac or Windows)?
Windows 10 22H2

Are you using ZoomOSC or ZoomISO?
ZoomOSC

Which version of ZoomOSC or ZoomISO are you using?
4.2.0

Are you using the Pro or Lite version for ZoomOSC/ZoomISO?
Pro

I have a show later today, i'll see if it happens during this one.

**Comment by DanielWilliamsMSC** [comment]
Had even more issues that usual today. 

Participant names showed correctly, however did not show the mic/video icons on their names. 
Was unabe to select them using this preset, would result in a crash 20% of the time when trying. 

![image](https://github.com/bitfocus/companion-module-zoom-osc-iso/assets/125619541/643cff56-b4ef-4cfc-9de9-10a79f3bee86)

**Comment by DanielWilliamsMSC** [comment]
Tested this again further after updating to RC2, still unable to select participants, nothing in logs when buttons are pressed. Trying another function results in an error to select a participant

**Comment by digitaldrummerj** [comment]
There is a pull request that was merged earlier today that that fixes a couple of bugs in the feedback system.  We are just waiting for it to be included in a release.  I will let you know when that release is available so you can test it again.

**Comment by digitaldrummerj** [comment]
@DanielWilliamsMSC can you give the latest beta (build 5989 or greater) a try and let me know if it fixes the crash you are experiencing?

**Comment by DanielWilliamsMSC** [comment]
@digitaldrummerj Beta version has fixed the issues i was having. Did pick up a couple other bugs

On first join all participants show as having mic enabled despite current status. 
Participants without audio connected show as having mic enabled. 
Putting participant 3 into the waiting room, caused participant 2 and 3's buttons to return to -, however both participant 2 and 3's mic icons stayed, participant 3 also stayed selected instead of unselecting automagically.

**Comment by digitaldrummerj** [comment]
@DanielWilliamsMSC 

1. I was not able to replicate the first join issue.  I tried it both with a meeting I was hosting and another meeting that I was just an attendee.  Could you stop and start your ZoomOSC connection in Companion and then try it again?  I do find that sometimes the ZoomOSC Companion module does not fully clear out all of the data so my BKM is to restart the connection between meetings to ensure I do not have odd behaviors like this.  
1. I was able able to replicate this one.  I had 2 participants in a meeting I joined that did not have audio connected and they both did not show the mic was live.
1.   I was not able to replicate this one.  For participants 2 and 3's buttons return to - that is indicating a crash of the module.  If you could open the module log up and do the action and see if an error is shown.  This could also be related to the 1st feedback above to restart the connection before joining the meeting.  If there is an error in the log please add it to this thread.  For  participant 3 staying selected, it is because the user is still in the meeting when you put them back into the waiting room.  The actions no longer clear out the selected user as it was requested that the selected user was not cleared out after an action so that you can take back to back actions on a participant.  The reason when you admit a participant to the meeting that they do not stay selected is because the user is seen as leaving the meeting and re-joining.

**Comment by JeffreyDavidsz** [comment]
Please be aware, as I'm reading this there is a lot of "update to version xxx". As there have been a lot of changes. Please take the time to rebuild your streamdeck, with the presest provided. So remove your old actions even the instance and start over. This can remove several issues you might be having.

**Comment by digitaldrummerj** [comment]
@DanielWilliamsMSC are you still having issues with the v3 production release of Companion?

**Comment by DanielWilliamsMSC** [comment]
No crashes I'm aware of. There has been mention that the mic feedback still wasn't working correctly, however i'll have to look into that one
