### ISSUE TITLE
Participant and Gallery Feedbacks Status

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#123]
As an added note:

I installed the latest Companion 3.0 beta (build 5975) and it would not run on my M1 Mac Mini running Ventura 13.3.1. The message I received said Companion is not supported on macOS 13.3.1, you must be running at least 10.15... which makes no sense. So, I installed a macOS update to macOS 13.4, and now the latest Companion 5975 will run. Just an FYI.

ZoomOSC Feedbacks Status

Running Companion 3.0+5975. I see that if in the module config I turn off "Participant Feedback with Icons" that my Gallery position-based buttons revert to the original feedback options, but my Participant position-based buttons do not.

Is there a known status of when we'll see the Participant position-based feedbacks also revert back to the original options?

I would also desire to know where this Feedbacks development is headed and what options will be available for us users/panel developers.

Thanks,

Jeff Widgren

**Comment by digitaldrummerj** [comment]
the "Participant Feedback with Icons" config option is for the new feedback to say if you just want the color blocks in the 4 corners with or without icons.  It does not change which feedback options are available for a button, just how the advanced feedback is displayed.

Long term, I believe that the feedback is going to be as the beta has it with both kinds of feedback: 1.) individual status feedback like before and 2.) the new advanced feedback that shows all of the statuses on the button as you saw recently.   There may be an additional position option added for the camera, mic, and active speaker status to be in the bottom 3rd of the button instead of the 4 corners.  For advanced feedback images they will be set within the module for the foreseeable future.

**Comment by digitaldrummerj** [comment]
For the position based buttons I will take a look this week and let you know.

**Comment by ZoomTestKitchen** [comment]
I was initially thinking that because I turned off the "Participant Feedback with Icons" option in the module config, that is what gave me back the original Feedbacks options on my Gallery position buttons.

This is apparently not the case.

NEW QUESTION:

Why does the new Active Feedback apply to Participant Position Buttons, but NOT Gallery Position Buttons?

All of my Participant Position Buttons do not display the original Feedback Options, although all of my Gallery Position buttons do display the original Feedback Options.

Are we going to provide a way to have access to the original feedback options for both Participant Position and Gallery Position buttons?

**Comment by digitaldrummerj** [comment]
@ZoomTestKitchen for the Participant Position buttons if it is not there it is a bug that I need to fix and that is what I will be looking at and getting fixed this week if it is not there.  The original feedback should be there for all of the participant types (position, gallery, group, etc).  I will verify that when I look at it and make sure that the presets for all of them have the feedback as well.  In the meantime, can you see if the position based preset has the old options?

For all of the new advanced feedback, there is an advanced feedback option that needs to be added to your existing buttons or if you want to fully go with the new feedback, there is a new preset advanced button that only has the advanced feedback on it.

**Comment by digitaldrummerj** [comment]
@ZoomTestKitchen I submitted a feedback to fix the position feedback and to update all of the advanced feedbacks to say (advanced) in the name so that it is clear which feedback is which when looking at the list to add.

**Comment by ZoomTestKitchen** [comment]
I am trying to understand why this Automated Active Feedback could not have been added as an additional option in the existing feedback list. Something similar to the list below.

 • Mic Live
 • Hand Raised
 • Camera On
 • Mic Off
 • Hand Lowered
 • Camera Off
 • Active Speaker
 • Automated Feedback (NEW)
 
BTW: the like items above need to be paired together, such as Hand Raised and Hand Lowered, etc.

Instead we have now ended-up with 8 additional Preset Groups that have been added due to the design of Automated Feedback. I feel like it has really taken away from the user-friendly presentation that previously existed. 

Right now in attempting to investigate why my buttons that are based on Participant Position only display the Automated Feedback option, it is impossible to tell which feedback option they are based on, because they are named identically. I realize now from your note above that you have submitted these labels to be uniquely named. And one more point, I now know that the feedback options on these buttons must be based on the Advanced Preset, but how is that possible when I designed these buttons prior to the existance of the Advanced Preset option? I'm feeling like I'm about to have to rebuild this panel as a consequence.

I just feel like moving forward users of this module are going to be confused.

Remind me, is the current stage of this feature development and integration here to stay, or is this simply a bandaid in the meantime while a new design is developed and written?

**Comment by digitaldrummerj** [comment]
@ZoomTestKitchen for existing buttons that are using the old feedback, you can add the advanced feedback manually to each button if you would like.  By having two sets of presets, it means that your existing panel that you have spent so much time on will continue to work out of the box, and if you drag a new participant from the original presets over it will also work in your configuration without having to change the out of the box feedback preset and then you can decide when you want to use the new advanced feedback by either manually adding it or using a new preset.

The reason that the new feedback could not be added to the existing list is that Companion has two different ways to do feedback that are mutually exclusive:

1. boolean (true/false)  is good for something that is simple like is mic on or not.  This feedback output is controlled by the user.
1. advanced feedback is useful when you need to look at a whole lot of values (mic, camera, hand raised, selected, active speaker, etc) and changed the display to indicate the combination and not just that a single value was turned on.  This feedback output is controlled by the module.

I agree with the confusion.  I would prefer to go with just having the participant presets use the new advanced presets but we are trying to work with you so that your existing configuration continues to work and make the new advanced feedback an opt-in.
