### ISSUE TITLE
VOTE to rollback the OSC/ISO module to only provide the original Feedback Options.

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#125]
The **Zoom OSC/ISO Companion Module** has been a lifesaver for many power users and producers. Providing the ability to accurately manage large to complex events, including one or many simultaneous Zoom Meetings/Webinars. Part of the automation piece has been its ability to provide us feedback on muted/live microphones, cameras, raised hands, etc.

One of the challenges or shortcomings that lives inside the core Companion product itself is its inability to support more than a single PNG file currently. The desire by many Zoom admins is to design a transparent png indicating a muted/unmuted mic, video camera, etc., but unfortunately, displaying a new (even transparent) png file replaces the previous one. So, combining statuses of multiple device states has proven very challenging.

There have been some recent efforts to improve this inside the Zoom OSC/ISO module. As thankful as I am for the efforts, many users find the actual deliverable undesirable. It would be perfect if it only delivered the necessary logic and left the creative design process to the user. Unfortunately, the initial release not only delivered the logic but also delivered a cosmetic design, therefore removing the creative possibilities from the module user.

I am proposing that the **Zoom OSC/ISO Module** be rolled back to a state that only provides the original Feedback Options I've listed below...

 • Mic Live
 • Hand Raised
 • Camera On
 • Mic Off
 • Hand Lowered
 • Camera Off
 • Active Speaker

This will provide time for further community feedback on what these new features should include and how they can be best presented to the user/designer.

If you have experienced these challenges and recent changes to the module and agree that it would be better to spend more time as a community of Zoom OSC/ISO users to better define the desired logic and final feature enhancement, please submit your supportive reply to this thread.

Jeff Widgren
Zoom Test Kitchen

**Comment by franklyray** [comment]
Jeff, I totally agree with you and support your request to have Zoom OSC/ISO Module be rolled back.

**Comment by digitaldrummerj** [comment]
I am not in support of rolling back the feedback.  The current solution that is in review is to bring back the original feedback and those presets and to add the new advanced feedback as an opt-in and new preset.  The solution in review gives those that want to use the original feedback the ability to do that without having to change anything in their current setup and then allow those that want to move to the new feedback that ability.  If you do not want to move to the new feedback, then you won't be forced to move to the new feedback.

The new feedback has worked fantastic for me and has been leaps and bounds better than the original feedback for me.  I have used the new feedback since April to run all of my events (5 events that were 1 day to 3 days long and averaged over 100 people on each event).   For me it would be a giant step backwards to remove that new advanced feedback option.

**Comment by MuddySchlegel** [comment]
I do NOT support rolling back the feedback to support the original feedback options ONLY. I support the current module in review that allows BOTH the original feedback options as well as the new feedback options. Both And.

**Comment by ZoomTestKitchen** [comment]
I understand that there will be a benefit to choosing the new or the old. I'm not the biggest fan of the old, but when compared to the new, I'll have no choice but to go with the original feature set. I dreamed about stepping up the feedback system and was the guy who proposed down to the binary level of how the new method might be implemented. I love the logic that has been created, but I want nothing to do with the execution and cosmetic deliverable.

Feedback used to be just a tab in Companion. Now, it is eight additional Preset Groups and zero ability to apply your own button design.

All I'm hoping for is a community forum that can submit ideas, wishes, and workflow ideas versus a new feature that's been developed by one person who claims that because it has worked great for them, it should work for everybody. That is not how development should be done or the reality.

This new logic is tightly attached to a cosmetic deliverable, and the group of users that serves are those who do not desire to add any customization to their button designs. But what about the rest of the Stream Deck panel developers who do create custom layouts and graphics?

This new feedback method has destroyed 100's of hours of development on my part by delivering a look versus the logic.

Yes, I can choose to go back to the old way, I get it, and I will. But, I will still carry my original desire to improve and enhance the feedback system like I initially did. I'll just have to wait until Core Companion starts supporting png layers.

**Comment by clafarge** [comment]
I will always prefer to have more data and more control over having decisions made for me. I favor the request as written.

**Comment by SNRSE** [comment]
I am against rolling back and urge the community to give developers time to address the changes wanted, and if you can't live with the new Feedback, you can always use an older version of Companion. 

Especially since the feedback that has been there in the past is there now and allows you to configure it like in the last versions. 
I need help finding what is missing and why "rolling back " would help at all as the original functionality is resorted. 
Maybe there only is an upgrade script missing? 

@ZoomTestKitchen  have you tried the latest beta that has the old feedback added again ?

**Comment by ZoomTestKitchen** [comment]
I ran the latest builds, yesterday that kinda has the old feedback options available. Meaning they were available for Gallery Position buttons, but not Participant Position buttons. This issue is getting looked into.

**Comment by digitaldrummerj** [comment]
> I ran the latest builds, yesterday that kinda has the old feedback options available. Meaning they were available for Gallery Position buttons, but not Participant Position buttons. This issue is getting looked into.

@ZoomTestKitchen I was able to find and fix the issue that you found yesterday.  Thank you for reporting the issue.  @JeffreyDavidsz merged the fix today.  The next step is for @JeffreyDavidsz to add it to a Companion release.

**Comment by ZoomTestKitchen** [comment]
Thank you for the status update. I’ll keep a look out for the new build.

**Comment by JeffreyDavidsz** [comment]
Updating as we speak

**Comment by digitaldrummerj** [comment]
@ZoomTestKitchen beta build 5989 includes the fix.  Can you give it a try and let us know if it fixes the issue that you reported?
