### ISSUE TITLE
<Ping> does not update callStatus

### ISSUE THREAD

**Issue by MattRogish** [bitfocus/companion-module-zoom-osc-iso#203]
Related to #168 :

On Companion v3.4.3: $(callStatus) variable is not updated after we issue a "ping" command, even though the ping response indicates "1" for call status.

Thanks!

**Comment by digitaldrummerj** [comment]
I am on Companion v3.4.2 and ZoomOSC 4.4.1 and I am not able to replicate this issue.  As far as I am aware there have been no update for this module in Companion v3.4.2 or v3.4.3.  In Companion v3.5, there are updates to the callStatus information.  

Can you give me a bit of detail on how you are using the callStatus variable?

**Comment by MattRogish** [comment]
We have a trigger on that variable and it only changes values if we disconnect / reconnect ZoomOSC module (ZoomOSC 4.5). My understanding is that the "ping" command would parse the response, e.g. 

`15:23:30.627 - Info: sending OSC message /zoomosc/pong 0 "ZOSC_4.5_MAC" 2 1 1 0 3 1`

And turn the "1" / "0" into appropriate values for $(<zoomosc>:callStatus) - except it doesn't change/update that variable at all.

**Comment by digitaldrummerj** [comment]
This issue is already fixed in Companion v3.5. 

In Companion v3.5 with ZoomOSC v4.5/ZoomISO v2.3, there are two variables:  callStatus and callStatusNumber.  The callStatus has In Meeting or Offline as possible values, while the callStatusNumber is the call status number from Zoom (sometimes).  The callStatusNumber is not entirely accurate except on the initial join or when you leave the meeting, as ping says 1 if it in meeting instead of the actual meeting status.

**Comment by digitaldrummerj** [comment]
@MattRogish were you able to get this working for you on Companion v3.5?

**Comment by MattRogish** [comment]
Hi @digitaldrummerj I haven't had a chance yet to do this as getting it on a device in beta-status is a bit cumbersome (we use MDM and everything is locked down) so I was waiting for 3.5 stable to land and retest a bunch of things.
