### ISSUE TITLE
Variables no longer displaying

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#41]
Only the first occurrence of 

`$(OSC___ISO_module:GalleryPosition01)    |    Gallery Position 1 `
`$(OSC___ISO_module:Participant001).      |    Participant 1`

are displaying under the Variables tabs. Referencing other positions and participants does work, but the ability to verify their value and/or copy the name of the variable is no longer available.

**Comment by JeffreyDavidsz** [comment]
That's intended. The list of variables became to long. All variables do work you just manually change the number.
for example $(OSC___ISO_module:GalleryPosition35).
If/When this is missed very much let me know including a usecase

**Comment by digitaldrummerj** [comment]
> That's intended. The list of variables became to long. All variables do work you just manually change the number.
> for example $(OSC___ISO_module:GalleryPosition35).
> If/When this is missed very much let me know including a usecase

@JeffreyDavidsz is this documented in the help?

**Comment by digitaldrummerj** [comment]
@ZoomTestKitchen I believe that many of us do this troubleshooting technique due to not having trust that the module is working correctly.   I would rather see us focus on making the module stable so that we can trust it.  As well, the available variables should be documented in the help of it isn’t already there.
