### ISSUE TITLE
OSC___ISO_module: Mute All Except Host mutes everybody including hosts and co-hosts

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#85]
OSC___ISO_module: Mute All: Mutes everybody except the OSC/ISO computer. This is ok.

**OSC___ISO_module: Mute All Except Host**

- I just saw this new action, but when I used it, it muted everybody including the hosts and co-hosts.

**Comment by digitaldrummerj** [comment]
I believe this was caused by looking for a specified user to be '' but it was undefined so it never selected the host from the host group.  In the PR, I removed the ability to set the userName in the Mute All Except Host action since it should always just get the callers from the host group.  If you need to specify for a user to not mute, then the action Mute All Except is the one that should be used.
